services:

    flux_se.sylius_stripe.provider.web_elements.create.params:
        class: FluxSE\SyliusStripePlugin\Provider\CompositeParamsProvider
        arguments:
            - !tagged_iterator flux_se.sylius_stripe.provider.web_elements.create.inner_params

    flux_se.sylius_stripe.provider.web_elements.create.amount:
        class: FluxSE\SyliusStripePlugin\Provider\WebElements\Create\AmountProvider
        tags:
            - name: flux_se.sylius_stripe.provider.web_elements.create.inner_params
              priority: -100

    flux_se.sylius_stripe.provider.web_elements.create.currency:
        class: FluxSE\SyliusStripePlugin\Provider\WebElements\Create\CurrencyProvider
        tags:
            - name: flux_se.sylius_stripe.provider.web_elements.create.inner_params
              priority: -200

    flux_se.sylius_stripe.provider.web_elements.create.payment_method_types:
        class: FluxSE\SyliusStripePlugin\Provider\PaymentMethodTypesProvider
        tags:
            - name: flux_se.sylius_stripe.provider.web_elements.create.inner_params
              priority: -300

    flux_se.sylius_stripe.provider.web_elements.create.capture_method.manual:
        class: FluxSE\SyliusStripePlugin\Provider\PaymentIntentCaptureMethodManualProvider
        tags:
            - name: flux_se.sylius_stripe.provider.web_elements.create.inner_params
              priority: -400

    flux_se.sylius_stripe.provider.web_elements.create.metadata:
        class: FluxSE\SyliusStripePlugin\Provider\CompositeMetadataParamsProvider
        arguments:
            - !tagged_iterator flux_se.sylius_stripe.provider.web_elements.create.metadata
        tags:
            - name: flux_se.sylius_stripe.provider.web_elements.create.inner_params
              priority: -500

    flux_se.sylius_stripe.provider.web_elements.create.metadata.token_hash:
        class: FluxSE\SyliusStripePlugin\Provider\TokenHashMetadataProvider
        tags:
            - name: flux_se.sylius_stripe.provider.web_elements.create.metadata
              priority: -100
