parameters:
    flux_se.sylius_stripe.stripe.client: \Stripe\StripeClient
    flux_se.sylius_stripe.stripe.client.chunk_size: 8192

services:
    
    flux_se.sylius_stripe.stripe.http_client:
        class: FluxSE\SyliusStripePlugin\Stripe\HttpClient\PsrClient
        arguments:
            - '@sylius.http_client'
            - '@sylius.http_client'
            - '@sylius.http_client'
            - '%flux_se.sylius_stripe.stripe.client.chunk_size%'
    
    flux_se.sylius_stripe.stripe.configurator:
        class: FluxSE\SyliusStripePlugin\Stripe\Configurator\StripeConfigurator
        arguments:
            - '@logger'
            - '@flux_se.sylius_stripe.stripe.http_client'
            - '@flux_se.sylius_stripe.stripe.http_client'
    FluxSE\SyliusStripePlugin\Stripe\Configurator\StripeConfiguratorInterface:
        alias: flux_se.sylius_stripe.stripe.configurator
    
    flux_se.sylius_stripe.stripe.factory.client:
        class: FluxSE\SyliusStripePlugin\Stripe\Factory\ClientFactory
        arguments:
            - '%flux_se.sylius_stripe.stripe.client%'
            - '@flux_se.sylius_stripe.stripe.configurator'
    FluxSE\SyliusStripePlugin\Stripe\Factory\ClientFactoryInterface:
        alias: flux_se.sylius_stripe.stripe.factory.client
    
    flux_se.sylius_stripe.stripe.resolver.event_resolver:
        class: FluxSE\SyliusStripePlugin\Stripe\Resolver\EventResolver
    FluxSE\SyliusStripePlugin\Stripe\Resolver\EventResolverInterface:
        alias: flux_se.sylius_stripe.stripe.resolver.event_resolver
