parameters:
    flux_se.sylius_stripe.stripe.client.chunk_size: 8192

services:

    FluxSE\SyliusStripePlugin\Stripe\HttpClient\PsrClient:
        abstract: true
        arguments:
            - '@sylius.http_client'
            - '@sylius.http_client'
            - '@sylius.http_client'
            - '%flux_se.sylius_stripe.stripe.client.chunk_size%'

    flux_se.sylius_stripe.stripe.http_client:
        parent: FluxSE\SyliusStripePlugin\Stripe\HttpClient\PsrClient

    flux_se.sylius_stripe.stripe.streaming_http_client:
        parent: FluxSE\SyliusStripePlugin\Stripe\HttpClient\PsrClient
