parameters:
    flux_se.sylius_stripe.stripe.client.chunk_size: 8192

services:

    FluxSE\SyliusStripePlugin\Stripe\HttpClient\PsrClient:
        abstract: true
        arguments:
            - '@Psr\Http\Client\ClientInterface'
            - '@Psr\Http\Message\RequestFactoryInterface'
            - '@Psr\Http\Message\StreamFactoryInterface'
            - '%flux_se.sylius_stripe.stripe.client.chunk_size%'

    flux_se.sylius_stripe.stripe.http_client:
        parent: FluxSE\SyliusStripePlugin\Stripe\HttpClient\PsrClient

    flux_se.sylius_stripe.stripe.streaming_http_client:
        parent: FluxSE\SyliusStripePlugin\Stripe\HttpClient\PsrClient
