sylius_twig_hooks:
    hooks:
        'sylius_admin.payment_method.create.content': &component
            form:
                props:
                    factoryName: '@=_context.resource.getGatewayConfig().getFactoryName()'
        'sylius_admin.payment_method.update.content': *component
        
        'sylius_admin.payment_method.create.content.form.sections.gateway_configuration.stripe_checkout': &form
            form:
                template: '@FluxSESyliusStripePlugin/admin/payment_method/form.html.twig'
                priority: 0
        'sylius_admin.payment_method.create.content.form.sections.gateway_configuration.stripe_web_elements': *form
        'sylius_admin.payment_method.update.content.form.sections.gateway_configuration.stripe_checkout': *form
        'sylius_admin.payment_method.update.content.form.sections.gateway_configuration.stripe_web_elements': *form
        
        'sylius_admin.payment_method.create.content.form.sections.gateway_configuration.stripe_checkout.form': &form_inner
            publishable_key:
                template: '@FluxSESyliusStripePlugin/admin/payment_method/form/publishable_key.html.twig'
                priority: 300
            secret_key:
                template: '@FluxSESyliusStripePlugin/admin/payment_method/form/secret_key.html.twig'
                priority: 200
            use_authorize:
                template: '@FluxSESyliusStripePlugin/admin/payment_method/form/use_authorize.html.twig'
                priority: 100
            webhook_secret_keys:
                template: '@FluxSESyliusStripePlugin/admin/payment_method/form/webhook_secret_keys.html.twig'
                priority: 0
        'sylius_admin.payment_method.create.content.form.sections.gateway_configuration.stripe_web_elements.form': *form_inner
        'sylius_admin.payment_method.update.content.form.sections.gateway_configuration.stripe_checkout.form': *form_inner
        'sylius_admin.payment_method.update.content.form.sections.gateway_configuration.stripe_web_elements.form': *form_inner

        'sylius_admin.payment_method.create.content.form.sections.gateway_configuration.stripe_checkout.form.webhook_secret_keys': &webhook_secret_keys
            webhook_secret_key:
                template: '@FluxSESyliusStripePlugin/admin/payment_method/form/webhook_secret_keys/webhook_secret_key.html.twig'
                priority: 0
        'sylius_admin.payment_method.create.content.form.sections.gateway_configuration.stripe_web_elements.form.webhook_secret_keys': *webhook_secret_keys
        'sylius_admin.payment_method.update.content.form.sections.gateway_configuration.stripe_checkout.form.webhook_secret_keys': *webhook_secret_keys
        'sylius_admin.payment_method.update.content.form.sections.gateway_configuration.stripe_web_elements.form.webhook_secret_keys': *webhook_secret_keys
